create table if not exists public.anime_reviews (
  id bigint generated by default as identity primary key,
  anime_mal_id integer not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  rating smallint not null check (rating between 1 and 10),
  review_text text not null check (char_length(trim(review_text)) between 10 and 2000),
  contains_spoilers boolean not null default false,
  helpful_count integer not null default 0,
  created_at timestamptz not null default now()
);

create unique index if not exists anime_reviews_user_anime_unique on public.anime_reviews (anime_mal_id, user_id);
create index if not exists anime_reviews_anime_created_idx on public.anime_reviews (anime_mal_id, created_at desc);
alter table public.anime_reviews enable row level security;

create policy "Anyone can read anime reviews" on public.anime_reviews for select using (true);
create policy "Signed-in users can create their own review" on public.anime_reviews for insert to authenticated with check (auth.uid() = user_id);
create policy "Users can update their own review" on public.anime_reviews for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can delete their own review" on public.anime_reviews for delete to authenticated using (auth.uid() = user_id);

create table if not exists public.anime_review_votes (
  review_id bigint not null references public.anime_reviews(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (review_id, user_id)
);
create index if not exists anime_review_votes_review_idx on public.anime_review_votes (review_id);
alter table public.anime_review_votes enable row level security;

create policy "Anyone can read review votes" on public.anime_review_votes for select using (true);
create policy "Signed-in users can vote once" on public.anime_review_votes for insert to authenticated with check (auth.uid() = user_id);
create policy "Users can remove their own vote" on public.anime_review_votes for delete to authenticated using (auth.uid() = user_id);
