-- ============================================================================
-- CATALOGUE — the site stops depending on Jikan/AniList at request time.
--
-- WHY
--   Every anime page is currently fetched live from Jikan. That caps the
--   catalogue at whatever a build can pull inside the 3 req/sec rate limit
--   (currently ~200 titles), makes page speed dependent on a third party,
--   and means a Jikan outage produces a blank site. Importing once into our
--   own tables removes the ceiling: one row is one URL, forever.
--
--   MAL/AniList stay as AUTHORING tools. The admin imports a title, the data
--   lands here, and the runtime reads only from this file.
--
-- DESIGN NOTES
--   · slug is a real column, unique, and never derived from a title at
--     read time. Titles get typos and translations; a slug computed on the
--     fly would silently change a URL that is already indexed, and any
--     change is written to `redirects` so old links 301.
--   · `status` (published/draft) is separate from the anime's own air
--     status. It is the switch that keeps drafts out of the sitemap.
--   · `rating` is OURS and defaults to null. MyAnimeList's score is kept
--     in `mal_score` and is never presented as our rating, because using a
--     third party's number as a rating is both misleading and a structured
--     data violation.
--   · This is additive. The existing `anime`, `episodes` and
--     `embed_sources` tables are left untouched; the new catalogue is
--     built alongside and the runtime switches over once it is populated.
-- ============================================================================

-- ─── anime ────────────────────────────────────────────────────────────────
create table if not exists public.anime_catalogue (
  id              bigint generated by default as identity primary key,

  -- identity
  slug            text        not null,
  title           text        not null,
  title_romaji    text,
  title_japanese  text,

  -- MAL id is the import key and the sameAs link. Kept even though URLs no
  -- longer depend on it, so a re-import can match an existing row.
  mal_id          integer,

  -- content
  synopsis        text,
  poster_url      text,
  banner_url      text,
  trailer_id      text,

  -- taxonomy (normalised names; joins below carry the structure)
  type            text,          -- TV | Movie | ONA | OVA | Special
  source          text,          -- Manga | Light Novel | Visual Novel
  air_status      text,          -- Finished Airing | Currently Airing | Not yet aired
  season          text,          -- winter | spring | summer | fall
  year            smallint,

  -- facts
  episodes_total  smallint,
  duration_min    smallint,
  age_rating      text,
  aired_from      date,
  aired_to        date,

  -- scores, kept deliberately separate
  rating          numeric(3,1) check (rating is null or rating between 0 and 10),
  mal_score       numeric(4,2),
  mal_rank        integer,
  popularity      integer,
  favorites       integer,

  -- publication control. Nothing ships to the sitemap unless this is
  -- 'published', which is what stops a half-imported title from being
  -- advertised as a thin page.
  status          text        not null default 'draft'
                                check (status in ('draft', 'published')),

  -- quality gate, set by the importer. Drives the "publish readiness"
  -- indicator in the admin so a page with no synopsis and no poster can
  -- never be published by accident.
  has_poster      boolean     not null default false,
  has_synopsis    boolean     not null default false,
  has_episodes    boolean     not null default false,

  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

-- The URL. Partial index so lookups of live titles are index-only, and
-- drafts are excluded without a filter.
create unique index if not exists anime_catalogue_slug_key
  on public.anime_catalogue (slug);
create index if not exists anime_catalogue_mal_idx
  on public.anime_catalogue (mal_id) where mal_id is not null;
create index if not exists anime_catalogue_published_idx
  on public.anime_catalogue (status, updated_at desc) where status = 'published';
create index if not exists anime_catalogue_year_idx
  on public.anime_catalogue (year desc) where status = 'published';

alter table public.anime_catalogue enable row level security;

-- DROP before CREATE. Unlike `create table if not exists`, `create policy`
-- has no such guard: re-running this migration raises
--   ERROR 42710: policy "..." already exists
-- and, because the SQL editor runs the whole file as one transaction, that
-- aborts every statement after this line. Dropping first makes the file
-- re-runnable, which matters because it is applied by hand in the dashboard
-- rather than by `supabase db push`, where a failed run is easy to repeat.
drop policy if exists "Anyone can read published anime" on public.anime_catalogue;
create policy "Anyone can read published anime"
  on public.anime_catalogue for select using (status = 'published');
-- ─── genres ───────────────────────────────────────────────────────────────
-- Genres are edited in the admin, so they are rows with an editable name
-- rather than a hardcoded table in a JS file. `mal_id` is nullable because
-- genres can exist that MAL has no id for.
create table if not exists public.genres (
  id       bigint generated by default as identity primary key,
  name     text        not null,
  slug     text        not null,
  mal_id   integer,
  is_hub   boolean     not null default false,   -- gets a /genre/:id page?
  position smallint    not null default 100,    -- display order
  unique (slug)
);
create unique index if not exists genres_mal_key on public.genres (mal_id) where mal_id is not null;

create table if not exists public.anime_genres (
  anime_id  bigint not null references public.anime_catalogue(id) on delete cascade,
  genre_id  bigint not null references public.genres(id) on delete cascade,
  is_primary boolean not null default false,
  primary key (anime_id, genre_id)
);
create index if not exists anime_genres_genre_idx on public.anime_genres (genre_id);

create table if not exists public.studios (
  id     bigint generated by default as identity primary key,
  name   text    not null,
  slug   text    not null,
  mal_id integer,
  unique (slug)
);
create unique index if not exists studios_mal_key on public.studios (mal_id) where mal_id is not null;

create table if not exists public.anime_studios (
  anime_id  bigint not null references public.anime_catalogue(id) on delete cascade,
  studio_id bigint not null references public.studios(id) on delete cascade,
  is_main   boolean not null default false,
  primary key (anime_id, studio_id)
);
create index if not exists anime_studios_studio_idx on public.anime_studios (studio_id);

-- ─── relations: powers /anime-like/X with no API call ────────────────────
-- This is the reason the "anime like X" pages stop costing a Jikan call per
-- title. Similarity is computed once at import and stored.
create table if not exists public.anime_relations (
  from_id    bigint not null references public.anime_catalogue(id) on delete cascade,
  to_id      bigint not null references public.anime_catalogue(id) on delete cascade,
  kind       text   not null,     -- sequel | prequel | side_story | alternative | parent | summary
  shared_genres smallint not null default 0,
  primary key (from_id, to_id, kind)
);
create index if not exists anime_relations_to_idx on public.anime_relations (to_id);
-- ─── episodes ─────────────────────────────────────────────────────────────
-- Extends what the existing `episodes` table has. That table carries
-- intro_start/intro_end only, which is enough to play a file but not enough
-- to build the episode list that gives a detail page its depth and its
-- internal links. title + synopsis + air_date are what a crawler reads.
create table if not exists public.catalogue_episodes (
  id              bigint generated by default as identity primary key,
  anime_id        bigint  not null references public.anime_catalogue(id) on delete cascade,
  episode_number  integer not null check (episode_number > 0),
  title           text,
  synopsis        text,
  thumbnail_url   text,
  air_date        date,
  duration_min    smallint,
  is_filler       boolean not null default false,
  created_at      timestamptz not null default now(),
  unique (anime_id, episode_number)
);
create index if not exists catalogue_episodes_anime_idx
  on public.catalogue_episodes (anime_id, episode_number);

-- ─── redirects ────────────────────────────────────────────────────────────
-- Written by the importer whenever a slug changes. The build reads this
-- table and emits 301s into vercel.json, so a renamed title never leaves a
-- dead link behind. This is the fix for the class of bug where a URL is
-- derived from a title that can be edited after indexing.
create table if not exists public.catalogue_redirects (
  from_path  text primary key,
  to_path    text not null,
  created_at timestamptz not null default now()
);

-- ─── updated_at maintenance ───────────────────────────────────────────────
create or replace function public.touch_updated_at() returns trigger
language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

drop trigger if exists anime_catalogue_touch on public.anime_catalogue;
create trigger anime_catalogue_touch
  before update on public.anime_catalogue
  for each row execute function public.touch_updated_at();

-- ─── publish gate ─────────────────────────────────────────────────────────
-- Refuses to mark a title published unless it has enough real content to be
-- worth ranking. This is the main defence against a self-hosted catalogue
-- filling its own sitemap with thin pages: an empty shell with a poster is
-- indexable but worthless, and a large catalogue of them reads as a
-- low-quality site.
--
-- This is a CHECK constraint rather than a trigger on purpose. Every field it
-- needs (has_poster, has_synopsis, has_episodes, synopsis) lives on the same
-- row, so the database can enforce it with no procedural code, and it applies
-- identically to INSERT and UPDATE. A trigger here would have to branch on
-- TG_OP to avoid reading OLD on an insert, where OLD is unassigned in
-- PL/pgSQL and raises at runtime.
--
-- The 200-char synopsis floor is the real gate: a title with only a title, a
-- poster and a genre list has nothing for a crawler to index.
alter table public.anime_catalogue
  drop constraint if exists anime_catalogue_publishable;
alter table public.anime_catalogue
  add constraint anime_catalogue_publishable check (
    status <> 'published'
    or (
      has_poster
      and has_synopsis
      and has_episodes
      and length(trim(coalesce(synopsis, ''))) >= 200
    )
  );